version: '3.8'

services:
    db:
        image: postgres:15
        container_name: pg_calorie_db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: calorie_db
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./01_create_weight_table.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
    pgdata:
